# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chang_phone.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(571, 460)
        Form.setStyleSheet("background-color: rgb(17, 17, 17);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.phone_number_lbl = QtWidgets.QLabel(Form)
        self.phone_number_lbl.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"font: 10pt \"华文琥珀\";")
        self.phone_number_lbl.setObjectName("phone_number_lbl")
        self.horizontalLayout.addWidget(self.phone_number_lbl)
        self.phone_number_edit = QtWidgets.QLineEdit(Form)
        self.phone_number_edit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"华文琥珀\";")
        self.phone_number_edit.setObjectName("phone_number_edit")
        self.horizontalLayout.addWidget(self.phone_number_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 9)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_phone_number_lbl = QtWidgets.QLabel(Form)
        self.new_phone_number_lbl.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"font: 10pt \"华文琥珀\";")
        self.new_phone_number_lbl.setObjectName("new_phone_number_lbl")
        self.horizontalLayout_2.addWidget(self.new_phone_number_lbl)
        self.new_phone_number_edit = QtWidgets.QLineEdit(Form)
        self.new_phone_number_edit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"华文琥珀\";")
        self.new_phone_number_edit.setObjectName("new_phone_number_edit")
        self.horizontalLayout_2.addWidget(self.new_phone_number_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 9)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sms_lbl = QtWidgets.QLabel(Form)
        self.sms_lbl.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"font: 10pt \"华文琥珀\";")
        self.sms_lbl.setObjectName("sms_lbl")
        self.horizontalLayout_3.addWidget(self.sms_lbl)
        self.sms_edit = QtWidgets.QLineEdit(Form)
        self.sms_edit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"华文琥珀\";")
        self.sms_edit.setObjectName("sms_edit")
        self.horizontalLayout_3.addWidget(self.sms_edit)
        self.sms_send_btn = QtWidgets.QPushButton(Form)
        self.sms_send_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.sms_send_btn.setObjectName("sms_send_btn")
        self.horizontalLayout_3.addWidget(self.sms_send_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 9)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.ensure_btn = QtWidgets.QPushButton(Form)
        self.ensure_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.ensure_btn.setObjectName("ensure_btn")
        self.horizontalLayout_4.addWidget(self.ensure_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.return_btn = QtWidgets.QPushButton(Form)
        self.return_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.return_btn.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.return_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.phone_number_lbl.setText(_translate("Form", "原手机号："))
        self.new_phone_number_lbl.setText(_translate("Form", "新手机号："))
        self.sms_lbl.setText(_translate("Form", "短信验证码;    "))
        self.sms_send_btn.setText(_translate("Form", "发送"))
        self.ensure_btn.setText(_translate("Form", "确定"))
        self.return_btn.setText(_translate("Form", "返回"))
