# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginFrom(object):
    def setupUi(self, loginFrom):
        loginFrom.setObjectName("loginFrom")
        loginFrom.resize(700, 600)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        loginFrom.setFont(font)
        loginFrom.setStyleSheet("background-color:rgb(17,17,17)")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(loginFrom)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unm_text = QtWidgets.QLabel(loginFrom)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.unm_text.setFont(font)
        self.unm_text.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"font: 10pt \"华文琥珀\";")
        self.unm_text.setObjectName("unm_text")
        self.horizontalLayout_2.addWidget(self.unm_text)
        self.unm_edit = QtWidgets.QLineEdit(loginFrom)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.unm_edit.setFont(font)
        self.unm_edit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"华文琥珀\";")
        self.unm_edit.setObjectName("unm_edit")
        self.horizontalLayout_2.addWidget(self.unm_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pwd_text = QtWidgets.QLabel(loginFrom)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pwd_text.setFont(font)
        self.pwd_text.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"font: 10pt \"华文琥珀\";")
        self.pwd_text.setObjectName("pwd_text")
        self.horizontalLayout_3.addWidget(self.pwd_text)
        self.pwd_edit = QtWidgets.QLineEdit(loginFrom)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pwd_edit.setFont(font)
        self.pwd_edit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"华文琥珀\";")
        self.pwd_edit.setObjectName("pwd_edit")
        self.horizontalLayout_3.addWidget(self.pwd_edit)
        self.view_pwd_btn = QtWidgets.QPushButton(loginFrom)
        self.view_pwd_btn.setStyleSheet("border:none")
        self.view_pwd_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/view_pwd_btn_close_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_pwd_btn.setIcon(icon)
        self.view_pwd_btn.setIconSize(QtCore.QSize(32, 32))
        self.view_pwd_btn.setObjectName("view_pwd_btn")
        self.horizontalLayout_3.addWidget(self.view_pwd_btn)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 8)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.login_btn = QtWidgets.QPushButton(loginFrom)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_4.addWidget(self.login_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.phone_login_btn = QtWidgets.QPushButton(loginFrom)
        self.phone_login_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.phone_login_btn.setObjectName("phone_login_btn")
        self.horizontalLayout_4.addWidget(self.phone_login_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.register_btn = QtWidgets.QPushButton(loginFrom)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.register_btn.setFont(font)
        self.register_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.register_btn.setObjectName("register_btn")
        self.horizontalLayout_4.addWidget(self.register_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)

        self.retranslateUi(loginFrom)
        QtCore.QMetaObject.connectSlotsByName(loginFrom)

    def retranslateUi(self, loginFrom):
        _translate = QtCore.QCoreApplication.translate
        loginFrom.setWindowTitle(_translate("loginFrom", "Stu_sys_login"))
        self.unm_text.setText(_translate("loginFrom", "用户名："))
        self.pwd_text.setText(_translate("loginFrom", "密码  ："))
        self.login_btn.setText(_translate("loginFrom", "登入"))
        self.phone_login_btn.setText(_translate("loginFrom", "手机号登入"))
        self.register_btn.setText(_translate("loginFrom", "注册"))
