# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 600)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color:rgb(17,17,17)")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.phone_lbl = QtWidgets.QLabel(Form)
        self.phone_lbl.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"font: 10pt \"华文琥珀\";")
        self.phone_lbl.setObjectName("phone_lbl")
        self.horizontalLayout.addWidget(self.phone_lbl)
        self.phone_edit = QtWidgets.QLineEdit(Form)
        self.phone_edit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"华文琥珀\";")
        self.phone_edit.setObjectName("phone_edit")
        self.horizontalLayout.addWidget(self.phone_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SMS_lbl = QtWidgets.QLabel(Form)
        self.SMS_lbl.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"font: 10pt \"华文琥珀\";")
        self.SMS_lbl.setObjectName("SMS_lbl")
        self.horizontalLayout_2.addWidget(self.SMS_lbl)
        self.SMS_edit = QtWidgets.QLineEdit(Form)
        self.SMS_edit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"华文琥珀\";")
        self.SMS_edit.setObjectName("SMS_edit")
        self.horizontalLayout_2.addWidget(self.SMS_edit)
        self.code_send_btn = QtWidgets.QPushButton(Form)
        self.code_send_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.code_send_btn.setObjectName("code_send_btn")
        self.horizontalLayout_2.addWidget(self.code_send_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login_btn = QtWidgets.QPushButton(Form)
        self.login_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_3.addWidget(self.login_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pwd_login_btn = QtWidgets.QPushButton(Form)
        self.pwd_login_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.pwd_login_btn.setObjectName("pwd_login_btn")
        self.horizontalLayout_3.addWidget(self.pwd_login_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.register_btn = QtWidgets.QPushButton(Form)
        self.register_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(57,57,57);\n"
"font: 10pt \"华文琥珀\";")
        self.register_btn.setObjectName("register_btn")
        self.horizontalLayout_3.addWidget(self.register_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.phone_lbl.setText(_translate("Form", "电话号码：        "))
        self.SMS_lbl.setText(_translate("Form", "短信验证码：     "))
        self.code_send_btn.setText(_translate("Form", "发送短信验证码"))
        self.login_btn.setText(_translate("Form", "登入"))
        self.pwd_login_btn.setText(_translate("Form", "密码登入"))
        self.register_btn.setText(_translate("Form", "注册"))
