# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\m_W.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background-color: rgb(17, 17, 17);\n"
"background-color: rgb(255, 234, 5);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0.477227, x2:1, y2:0, stop:0 rgba(17, 17, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:10px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.weather_lbl = QtWidgets.QLabel(self.frame_2)
        self.weather_lbl.setGeometry(QtCore.QRect(976, 41, 251, 21))
        self.weather_lbl.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgb(17, 17, 17);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.weather_lbl.setObjectName("weather_lbl")
        self.unm_lbl = QtWidgets.QLabel(self.frame_2)
        self.unm_lbl.setGeometry(QtCore.QRect(350, 40, 181, 21))
        self.unm_lbl.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgb(17, 17, 17);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.unm_lbl.setObjectName("unm_lbl")
        self.main_date_lbl = QtWidgets.QLabel(self.frame_2)
        self.main_date_lbl.setGeometry(QtCore.QRect(630, 40, 201, 21))
        self.main_date_lbl.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgb(17, 17, 17);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.main_date_lbl.setObjectName("main_date_lbl")
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setStyleSheet("background-color: rgb(17, 17, 17);\n"
"border-radius:10px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.video_btn = QtWidgets.QPushButton(self.frame_3)
        self.video_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.video_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-视频管理.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.video_btn.setIcon(icon)
        self.video_btn.setIconSize(QtCore.QSize(50, 50))
        self.video_btn.setObjectName("video_btn")
        self.verticalLayout_4.addWidget(self.video_btn)
        self.road_btn = QtWidgets.QPushButton(self.frame_3)
        self.road_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.road_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-记录仪.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.road_btn.setIcon(icon1)
        self.road_btn.setIconSize(QtCore.QSize(50, 50))
        self.road_btn.setObjectName("road_btn")
        self.verticalLayout_4.addWidget(self.road_btn)
        self.photo_btn = QtWidgets.QPushButton(self.frame_3)
        self.photo_btn.setBaseSize(QtCore.QSize(7, 6))
        self.photo_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.photo_btn.setStyleSheet("border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.photo_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-截图.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.photo_btn.setIcon(icon2)
        self.photo_btn.setIconSize(QtCore.QSize(50, 50))
        self.photo_btn.setObjectName("photo_btn")
        self.verticalLayout_4.addWidget(self.photo_btn)
        self.cab_btn = QtWidgets.QPushButton(self.frame_3)
        self.cab_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.cab_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-4G图传.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cab_btn.setIcon(icon3)
        self.cab_btn.setIconSize(QtCore.QSize(50, 50))
        self.cab_btn.setObjectName("cab_btn")
        self.verticalLayout_4.addWidget(self.cab_btn)
        self.main_btn = QtWidgets.QPushButton(self.frame_3)
        self.main_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.main_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-首页.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_btn.setIcon(icon4)
        self.main_btn.setIconSize(QtCore.QSize(50, 50))
        self.main_btn.setObjectName("main_btn")
        self.verticalLayout_4.addWidget(self.main_btn)
        self.user_btn = QtWidgets.QPushButton(self.frame_3)
        self.user_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.user_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-用户管理.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon5)
        self.user_btn.setIconSize(QtCore.QSize(50, 50))
        self.user_btn.setObjectName("user_btn")
        self.verticalLayout_4.addWidget(self.user_btn)
        self.t_photo_btn = QtWidgets.QPushButton(self.frame_3)
        self.t_photo_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.t_photo_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-相机.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_photo_btn.setIcon(icon6)
        self.t_photo_btn.setIconSize(QtCore.QSize(50, 50))
        self.t_photo_btn.setObjectName("t_photo_btn")
        self.verticalLayout_4.addWidget(self.t_photo_btn)
        self.horizontalLayout.addWidget(self.frame_3)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setStyleSheet("background-color:rgb(255, 47, 50);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.cab_W = QtWidgets.QWidget()
        self.cab_W.setStyleSheet("")
        self.cab_W.setObjectName("cab_W")
        self.cab_video_lbl = QtWidgets.QLabel(self.cab_W)
        self.cab_video_lbl.setGeometry(QtCore.QRect(20, 40, 881, 491))
        self.cab_video_lbl.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.cab_video_lbl.setObjectName("cab_video_lbl")
        self.cab_reminder_lbl = QtWidgets.QLabel(self.cab_W)
        self.cab_reminder_lbl.setGeometry(QtCore.QRect(380, 0, 101, 31))
        self.cab_reminder_lbl.setStyleSheet("color: rgb(255, 165, 19);\n"
"font: 87 12pt \"Arial Black\";")
        self.cab_reminder_lbl.setObjectName("cab_reminder_lbl")
        self.cab_record_begin_btn = QtWidgets.QPushButton(self.cab_W)
        self.cab_record_begin_btn.setGeometry(QtCore.QRect(430, 540, 71, 51))
        self.cab_record_begin_btn.setStyleSheet("border:none")
        self.cab_record_begin_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-录制.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cab_record_begin_btn.setIcon(icon7)
        self.cab_record_begin_btn.setIconSize(QtCore.QSize(50, 50))
        self.cab_record_begin_btn.setObjectName("cab_record_begin_btn")
        self.stackedWidget.addWidget(self.cab_W)
        self.road_W = QtWidgets.QWidget()
        self.road_W.setStyleSheet("")
        self.road_W.setObjectName("road_W")
        self.road_video_lbl = QtWidgets.QLabel(self.road_W)
        self.road_video_lbl.setGeometry(QtCore.QRect(30, 40, 1081, 671))
        self.road_video_lbl.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.road_video_lbl.setObjectName("road_video_lbl")
        self.road_reminder_lbl = QtWidgets.QLabel(self.road_W)
        self.road_reminder_lbl.setGeometry(QtCore.QRect(270, 0, 281, 21))
        self.road_reminder_lbl.setStyleSheet("color: rgb(255, 165, 19);\n"
"font: 87 12pt \"Arial Black\";")
        self.road_reminder_lbl.setObjectName("road_reminder_lbl")
        self.road_screenshot_btn = QtWidgets.QPushButton(self.road_W)
        self.road_screenshot_btn.setGeometry(QtCore.QRect(550, 730, 51, 51))
        self.road_screenshot_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.road_screenshot_btn.setStyleSheet("border:none")
        self.road_screenshot_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-相机(实).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.road_screenshot_btn.setIcon(icon8)
        self.road_screenshot_btn.setIconSize(QtCore.QSize(40, 40))
        self.road_screenshot_btn.setObjectName("road_screenshot_btn")
        self.stackedWidget.addWidget(self.road_W)
        self.t_photo_W = QtWidgets.QWidget()
        self.t_photo_W.setObjectName("t_photo_W")
        self.t_photo_capture_lbl = QtWidgets.QLabel(self.t_photo_W)
        self.t_photo_capture_lbl.setGeometry(QtCore.QRect(30, 30, 1091, 591))
        self.t_photo_capture_lbl.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.t_photo_capture_lbl.setText("")
        self.t_photo_capture_lbl.setObjectName("t_photo_capture_lbl")
        self.t_photo_show_lbl = QtWidgets.QLabel(self.t_photo_W)
        self.t_photo_show_lbl.setGeometry(QtCore.QRect(900, 640, 221, 131))
        self.t_photo_show_lbl.setStyleSheet("")
        self.t_photo_show_lbl.setText("")
        self.t_photo_show_lbl.setObjectName("t_photo_show_lbl")
        self.t_photo_take_photo_btn = QtWidgets.QPushButton(self.t_photo_W)
        self.t_photo_take_photo_btn.setGeometry(QtCore.QRect(530, 690, 91, 51))
        self.t_photo_take_photo_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.t_photo_take_photo_btn.setObjectName("t_photo_take_photo_btn")
        self.stackedWidget.addWidget(self.t_photo_W)
        self.nag_W = QtWidgets.QWidget()
        self.nag_W.setObjectName("nag_W")
        self.toolButton = QtWidgets.QToolButton(self.nag_W)
        self.toolButton.setGeometry(QtCore.QRect(290, 380, 201, 18))
        self.toolButton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.toolButton.setObjectName("toolButton")
        self.stackedWidget.addWidget(self.nag_W)
        self.main_W = QtWidgets.QWidget()
        self.main_W.setObjectName("main_W")
        self.stackedWidget.addWidget(self.main_W)
        self.video_W = myVideoWidget()
        self.video_W.setObjectName("video_W")
        self.video_dateEdit = QtWidgets.QDateEdit(self.video_W)
        self.video_dateEdit.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.video_dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px")
        self.video_dateEdit.setObjectName("video_dateEdit")
        self.video_show_lbl = QtWidgets.QLabel(self.video_W)
        self.video_show_lbl.setGeometry(QtCore.QRect(180, 30, 931, 671))
        self.video_show_lbl.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.video_show_lbl.setText("")
        self.video_show_lbl.setObjectName("video_show_lbl")
        self.video_play_btn = QtWidgets.QPushButton(self.video_W)
        self.video_play_btn.setGeometry(QtCore.QRect(570, 740, 75, 31))
        self.video_play_btn.setStyleSheet("border:none")
        self.video_play_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-播放(实).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.video_play_btn.setIcon(icon9)
        self.video_play_btn.setIconSize(QtCore.QSize(20, 20))
        self.video_play_btn.setObjectName("video_play_btn")
        self.horizontalSlider = QtWidgets.QSlider(self.video_W)
        self.horizontalSlider.setGeometry(QtCore.QRect(190, 720, 911, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.video_speedx1_box = QtWidgets.QRadioButton(self.video_W)
        self.video_speedx1_box.setGeometry(QtCore.QRect(630, 0, 61, 16))
        self.video_speedx1_box.setStyleSheet("border:none;\n"
"font: 10pt \"华文琥珀\";\n"
"color: rgb(127, 127, 127);")
        self.video_speedx1_box.setObjectName("video_speedx1_box")
        self.video_speedx05_box = QtWidgets.QRadioButton(self.video_W)
        self.video_speedx05_box.setGeometry(QtCore.QRect(490, 0, 71, 21))
        self.video_speedx05_box.setStyleSheet("border:none;\n"
"font: 10pt \"华文琥珀\";\n"
"color: rgb(127, 127, 127);")
        self.video_speedx05_box.setObjectName("video_speedx05_box")
        self.video_speedx2_box = QtWidgets.QRadioButton(self.video_W)
        self.video_speedx2_box.setGeometry(QtCore.QRect(770, 0, 61, 16))
        self.video_speedx2_box.setStyleSheet("border:none;\n"
"font: 10pt \"华文琥珀\";\n"
"color: rgb(127, 127, 127);")
        self.video_speedx2_box.setObjectName("video_speedx2_box")
        self.video_open_btn = QtWidgets.QPushButton(self.video_W)
        self.video_open_btn.setGeometry(QtCore.QRect(0, 710, 81, 31))
        self.video_open_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.video_open_btn.setObjectName("video_open_btn")
        self.pushButton = QtWidgets.QPushButton(self.video_W)
        self.pushButton.setGeometry(QtCore.QRect(720, 740, 75, 21))
        self.pushButton.setStyleSheet("border:none;\n"
"font: 15pt \"华文琥珀\";\n"
"color: rgb(127, 127, 127);")
        self.pushButton.setObjectName("pushButton")
        self.video_back_btn = QtWidgets.QPushButton(self.video_W)
        self.video_back_btn.setGeometry(QtCore.QRect(430, 740, 75, 23))
        self.video_back_btn.setStyleSheet("border:none;\n"
"font: 15pt \"华文琥珀\";\n"
"color: rgb(127, 127, 127);")
        self.video_back_btn.setObjectName("video_back_btn")
        self.video_list_view = QtWidgets.QListWidget(self.video_W)
        self.video_list_view.setGeometry(QtCore.QRect(10, 60, 151, 641))
        self.video_list_view.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.video_list_view.setObjectName("video_list_view")
        self.video_open_btn_2 = QtWidgets.QPushButton(self.video_W)
        self.video_open_btn_2.setGeometry(QtCore.QRect(90, 710, 91, 31))
        self.video_open_btn_2.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.video_open_btn_2.setObjectName("video_open_btn_2")
        self.stackedWidget.addWidget(self.video_W)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.music_play_btn = QtWidgets.QPushButton(self.page)
        self.music_play_btn.setGeometry(QtCore.QRect(530, 700, 75, 41))
        self.music_play_btn.setStyleSheet("border:none")
        self.music_play_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(".\\../resource/icon/video_play_btn_begin_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.music_play_btn.setIcon(icon10)
        self.music_play_btn.setIconSize(QtCore.QSize(40, 40))
        self.music_play_btn.setObjectName("music_play_btn")
        self.music_prev_btn = QtWidgets.QPushButton(self.page)
        self.music_prev_btn.setGeometry(QtCore.QRect(430, 700, 71, 51))
        self.music_prev_btn.setStyleSheet("border:none;\n"
"color:rgb(87,87,87);\n"
"font: 25pt \"华文琥珀\";")
        self.music_prev_btn.setObjectName("music_prev_btn")
        self.music_show_list = QtWidgets.QListWidget(self.page)
        self.music_show_list.setGeometry(QtCore.QRect(70, 70, 1001, 571))
        self.music_show_list.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(20, 20, 20);\n"
"color: rgb(127, 127, 127)")
        self.music_show_list.setObjectName("music_show_list")
        self.music_slider = QtWidgets.QSlider(self.page)
        self.music_slider.setGeometry(QtCore.QRect(69, 660, 1001, 20))
        self.music_slider.setOrientation(QtCore.Qt.Horizontal)
        self.music_slider.setObjectName("music_slider")
        self.music_next_btn = QtWidgets.QPushButton(self.page)
        self.music_next_btn.setGeometry(QtCore.QRect(630, 700, 71, 51))
        self.music_next_btn.setStyleSheet("border:none;\n"
"color:rgb(87,87,87);\n"
"font: 25pt \"华文琥珀\";")
        self.music_next_btn.setObjectName("music_next_btn")
        self.music_add_btn = QtWidgets.QPushButton(self.page)
        self.music_add_btn.setGeometry(QtCore.QRect(790, 702, 171, 41))
        self.music_add_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.music_add_btn.setObjectName("music_add_btn")
        self.stackedWidget.addWidget(self.page)
        self.photo_W = QtWidgets.QWidget()
        self.photo_W.setObjectName("photo_W")
        self.photo_show_lbl = QtWidgets.QLabel(self.photo_W)
        self.photo_show_lbl.setGeometry(QtCore.QRect(230, 10, 891, 711))
        self.photo_show_lbl.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.photo_show_lbl.setText("")
        self.photo_show_lbl.setObjectName("photo_show_lbl")
        self.photo_del_btn = QtWidgets.QPushButton(self.photo_W)
        self.photo_del_btn.setGeometry(QtCore.QRect(620, 740, 111, 31))
        self.photo_del_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.photo_del_btn.setObjectName("photo_del_btn")
        self.photo_list_view = QtWidgets.QListWidget(self.photo_W)
        self.photo_list_view.setGeometry(QtCore.QRect(10, 10, 201, 711))
        self.photo_list_view.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.photo_list_view.setObjectName("photo_list_view")
        self.photo_next_btn = QtWidgets.QPushButton(self.photo_W)
        self.photo_next_btn.setGeometry(QtCore.QRect(900, 740, 111, 31))
        self.photo_next_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.photo_next_btn.setObjectName("photo_next_btn")
        self.photo_prev_btn = QtWidgets.QPushButton(self.photo_W)
        self.photo_prev_btn.setGeometry(QtCore.QRect(330, 740, 111, 31))
        self.photo_prev_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.photo_prev_btn.setObjectName("photo_prev_btn")
        self.photo_open_btn_2 = QtWidgets.QPushButton(self.photo_W)
        self.photo_open_btn_2.setGeometry(QtCore.QRect(20, 730, 91, 31))
        self.photo_open_btn_2.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.photo_open_btn_2.setObjectName("photo_open_btn_2")
        self.photo_open_btn_3 = QtWidgets.QPushButton(self.photo_W)
        self.photo_open_btn_3.setGeometry(QtCore.QRect(120, 730, 91, 31))
        self.photo_open_btn_3.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.photo_open_btn_3.setObjectName("photo_open_btn_3")
        self.stackedWidget.addWidget(self.photo_W)
        self.user_W = QtWidgets.QWidget()
        self.user_W.setObjectName("user_W")
        self.user_img_lbl = QtWidgets.QLabel(self.user_W)
        self.user_img_lbl.setGeometry(QtCore.QRect(40, 20, 671, 641))
        self.user_img_lbl.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.user_img_lbl.setObjectName("user_img_lbl")
        self.user_unm_lbl = QtWidgets.QLabel(self.user_W)
        self.user_unm_lbl.setGeometry(QtCore.QRect(740, 50, 81, 61))
        self.user_unm_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;\n"
"font: 18pt \"幼圆\";")
        self.user_unm_lbl.setObjectName("user_unm_lbl")
        self.user_phone_lbl = QtWidgets.QLabel(self.user_W)
        self.user_phone_lbl.setGeometry(QtCore.QRect(740, 330, 71, 71))
        self.user_phone_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;\n"
"font: 18pt \"幼圆\";")
        self.user_phone_lbl.setObjectName("user_phone_lbl")
        self.user_unmData_lbl = QtWidgets.QLabel(self.user_W)
        self.user_unmData_lbl.setGeometry(QtCore.QRect(850, 50, 271, 61))
        self.user_unmData_lbl.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Agency FB\";")
        self.user_unmData_lbl.setObjectName("user_unmData_lbl")
        self.user_phoneData_lbl = QtWidgets.QLabel(self.user_W)
        self.user_phoneData_lbl.setGeometry(QtCore.QRect(850, 330, 271, 71))
        self.user_phoneData_lbl.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Agency FB\";")
        self.user_phoneData_lbl.setObjectName("user_phoneData_lbl")
        self.user_bind_phone_btn = QtWidgets.QPushButton(self.user_W)
        self.user_bind_phone_btn.setGeometry(QtCore.QRect(990, 560, 101, 61))
        self.user_bind_phone_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.user_bind_phone_btn.setObjectName("user_bind_phone_btn")
        self.user_upload_img_btn = QtWidgets.QPushButton(self.user_W)
        self.user_upload_img_btn.setGeometry(QtCore.QRect(270, 680, 161, 81))
        self.user_upload_img_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.user_upload_img_btn.setObjectName("user_upload_img_btn")
        self.user_change_pwd_btn = QtWidgets.QPushButton(self.user_W)
        self.user_change_pwd_btn.setGeometry(QtCore.QRect(770, 560, 101, 61))
        self.user_change_pwd_btn.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(68, 64, 67);\n"
"color: rgb(127, 127, 127);\n"
"")
        self.user_change_pwd_btn.setObjectName("user_change_pwd_btn")
        self.stackedWidget.addWidget(self.user_W)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setStyleSheet("background-color: rgb(17, 17, 17);\n"
"border-radius:10px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/油箱.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon11)
        self.pushButton_5.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/灯光.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon12)
        self.pushButton_4.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/空调.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon13)
        self.pushButton_3.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/座椅.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon14)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border-radius:10px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nag_btn = QtWidgets.QPushButton(self.frame)
        self.nag_btn.setToolTipDuration(-12)
        self.nag_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.nag_btn.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-车载GPS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nag_btn.setIcon(icon15)
        self.nag_btn.setIconSize(QtCore.QSize(70, 70))
        self.nag_btn.setObjectName("nag_btn")
        self.horizontalLayout_2.addWidget(self.nag_btn)
        self.phone_btn = QtWidgets.QPushButton(self.frame)
        self.phone_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.phone_btn.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/mti-电话.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.phone_btn.setIcon(icon16)
        self.phone_btn.setIconSize(QtCore.QSize(70, 70))
        self.phone_btn.setObjectName("phone_btn")
        self.horizontalLayout_2.addWidget(self.phone_btn)
        self.music_btn = QtWidgets.QPushButton(self.frame)
        self.music_btn.setStyleSheet("color:rgb(116, 116, 116);\n"
"border:none;\n"
"font: 15pt \"华文琥珀\";")
        self.music_btn.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(".\\../../.designer/backup/icon/音乐.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.music_btn.setIcon(icon17)
        self.music_btn.setIconSize(QtCore.QSize(70, 70))
        self.music_btn.setObjectName("music_btn")
        self.horizontalLayout_2.addWidget(self.music_btn)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.weather_lbl.setText(_translate("Form", "天气:小雨，温度:8-10℃"))
        self.unm_lbl.setText(_translate("Form", "你好，****"))
        self.main_date_lbl.setText(_translate("Form", "2024.02.26 16:17:03"))
        self.cab_video_lbl.setText(_translate("Form", "我是cabW，00000000"))
        self.cab_reminder_lbl.setText(_translate("Form", "左顾右盼"))
        self.road_video_lbl.setText(_translate("Form", "我是roadW，11111111"))
        self.road_reminder_lbl.setText(_translate("Form", "左顾右盼"))
        self.t_photo_take_photo_btn.setText(_translate("Form", "拍照"))
        self.toolButton.setText(_translate("Form", "..."))
        self.video_speedx1_box.setText(_translate("Form", "1倍速"))
        self.video_speedx05_box.setText(_translate("Form", "0.5倍速"))
        self.video_speedx2_box.setText(_translate("Form", "2倍速"))
        self.video_open_btn.setText(_translate("Form", "添加视频"))
        self.pushButton.setText(_translate("Form", "》》"))
        self.video_back_btn.setText(_translate("Form", "《《 "))
        self.video_open_btn_2.setText(_translate("Form", "删除视频"))
        self.music_prev_btn.setText(_translate("Form", "<<"))
        self.music_next_btn.setText(_translate("Form", ">>"))
        self.music_add_btn.setText(_translate("Form", "添加音频"))
        self.photo_del_btn.setText(_translate("Form", "删除"))
        self.photo_next_btn.setText(_translate("Form", "下一个"))
        self.photo_prev_btn.setText(_translate("Form", "上一个"))
        self.photo_open_btn_2.setText(_translate("Form", "添加照片"))
        self.photo_open_btn_3.setText(_translate("Form", "删除照片"))
        self.user_img_lbl.setText(_translate("Form", "我是userW，666666"))
        self.user_unm_lbl.setText(_translate("Form", "用户名:"))
        self.user_phone_lbl.setText(_translate("Form", "电话:"))
        self.user_unmData_lbl.setText(_translate("Form", "WWEE@223"))
        self.user_phoneData_lbl.setText(_translate("Form", "15060058325"))
        self.user_bind_phone_btn.setText(_translate("Form", "绑定新号码"))
        self.user_upload_img_btn.setText(_translate("Form", "上传新头像"))
        self.user_change_pwd_btn.setText(_translate("Form", "修改密码"))
from myVideoWidget import myVideoWidget
